version: '3.8'

services:
  interview-local:
    build: ./services/interview
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_REGION=us-east-1
      - LAMBDA_FUNCTION_NAME=spool-create-thread
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./services/interview:/app
    command: python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8080

  # Reverse proxy for local development
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - interview-local 